package hwg.dao.generate.mapper;

import hwg.model.Roleprivilege;
import hwg.model.RoleprivilegeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleprivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbg.generated Wed Feb 05 22:16:49 CST 2020
     */
    long countByExample(RoleprivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbg.generated Wed Feb 05 22:16:49 CST 2020
     */
    int deleteByExample(RoleprivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbg.generated Wed Feb 05 22:16:49 CST 2020
     */
    int insert(Roleprivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbg.generated Wed Feb 05 22:16:49 CST 2020
     */
    int insertSelective(Roleprivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbg.generated Wed Feb 05 22:16:49 CST 2020
     */
    List<Roleprivilege> selectByExample(RoleprivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbg.generated Wed Feb 05 22:16:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") Roleprivilege record, @Param("example") RoleprivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbg.generated Wed Feb 05 22:16:49 CST 2020
     */
    int updateByExample(@Param("record") Roleprivilege record, @Param("example") RoleprivilegeExample example);
}